# Change these first
owner: dstanecki # Your GitHub organization or username, where this repository lives
repo: zhf-upptime # The name of this repository

sites:
  - name: Zillow Housing Forecast
    url: https://zhf.danielstanecki.com/ready
    expectedStatusCodes:
      - 200
  - name: (Dev) Zillow Housing Forecast
    url: https://zhf-dev.danielstanecki.com/ready
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /zhf-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Tracking the external uptime and response latency of my Zillow Housing Forecast app
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
